# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/yunji0387/express-auth-server/discussions
    about: Use GitHub Discussions to ask questions and/or open discussion topics.
  - name: Documentation
    url: https://github.com/yunji0387/express-auth-server?tab=readme-ov-file#readme
    about: Read the documentation.